# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHxOD7-hlqMyc4lcq3jPCuk58wAyN1ts
"""

import pandas as pd
import joblib

label_encoders = joblib.load('RF_encoders.joblib')
model = joblib.load('RFclassifier.joblib')

input_cols = ['POSTED_SPEED_LIMIT', 'WEATHER_CONDITION', 'LIGHTING_CONDITION',
       'TRAFFICWAY_TYPE', 'ALIGNMENT',
       'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'PRIM_CONTRIBUTORY_CAUSE',
       'SEC_CONTRIBUTORY_CAUSE', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK',
       'CRASH_MONTH', 'MANEUVER', 'SEX', 'AGE']

def custom_predict(new_sample):
    new_df = pd.DataFrame([new_sample])
    for col in input_cols:
        new_df[col] = label_encoders[col].transform(new_df[col].astype(str))
    prediction = model.predict(new_df)
    crash_type = label_encoders['FIRST_CRASH_TYPE'].inverse_transform(prediction)[0]
    return crash_type

new_sample = {
    'POSTED_SPEED_LIMIT': '40',
    'WEATHER_CONDITION': 'CLEAR',
    'LIGHTING_CONDITION': 'DAYLIGHT',
    'TRAFFICWAY_TYPE': 'FOUR WAY',
    'ALIGNMENT': 'STRAIGHT AND LEVEL',
    'ROADWAY_SURFACE_COND': 'DRY',
    'ROAD_DEFECT': 'UNKNOWN',
    'PRIM_CONTRIBUTORY_CAUSE': 'FAILING TO REDUCE SPEED TO AVOID CRASH',
    'SEC_CONTRIBUTORY_CAUSE': 'DISTRACTION - FROM INSIDE VEHICLE',
    'CRASH_HOUR': '12.0',
    'CRASH_DAY_OF_WEEK':'6.0',
    'CRASH_MONTH':'8.0',
    'MANEUVER':'STRAIGHT AHEAD',
    'SEX':'M',
    'AGE': '35.0'
}

print(f"Predicted Crash Type: {custom_predict(new_sample)}")