# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHxOD7-hlqMyc4lcq3jPCuk58wAyN1ts
"""

import pandas as pd
import joblib

label_encoders = joblib.load('LGBM_encoders.joblib')
nb_model = joblib.load('lightGBM.joblib')

input_cols = ['POSTED_SPEED_LIMIT', 'WEATHER_CONDITION', 'LIGHTING_CONDITION',
       'TRAFFICWAY_TYPE', 'ALIGNMENT',
       'ROADWAY_SURFACE_COND', 'ROAD_DEFECT', 'PRIM_CONTRIBUTORY_CAUSE',
       'SEC_CONTRIBUTORY_CAUSE', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK',
       'CRASH_MONTH', 'MANEUVER', 'SEX', 'AGE']

new_sample = {
    'POSTED_SPEED_LIMIT': '50',
    'WEATHER_CONDITION': 'RAIN',
    'LIGHTING_CONDITION': 'DAYLIGHT',
    'TRAFFICWAY_TYPE': 'ONE-WAY',
    'ALIGNMENT': 'STRAIGHT AND LEVEL',
    'ROADWAY_SURFACE_COND': 'WET',
    'ROAD_DEFECT': 'UNKNOWN',
    'PRIM_CONTRIBUTORY_CAUSE': 'IMPROPER TURNING/NO SIGNAL',
    'SEC_CONTRIBUTORY_CAUSE': 'UNABLE TO DETERMINE',
    'CRASH_HOUR': '17',
    'CRASH_DAY_OF_WEEK':'6',
    'CRASH_MONTH':'8',
    'MANEUVER':'STRAIGHT AHEAD',
    'SEX':'M',
    'AGE': '35.0'
}

new_df = pd.DataFrame([new_sample])
for col in input_cols:
    val = str(new_df.at[0, col])
    new_df[col] = label_encoders[col].transform([val])
prediction = nb_model.predict(new_df)
print(f"Accident type: {label_encoders['FIRST_CRASH_TYPE'].inverse_transform(prediction)[0]}")